repo_list:
  config:
    url: "git@github.com:thevndrew/nix-config.git"
    directory: "nix-config"
  services:
    url: "git@github.com:thevndrew/container-services.git"
    directory: "services"
  secrets:
    url: "git@github.com:thevndrew/nix-secrets.git"
    directory: "repos/nix-secrets"
  packages:
    url: "git@github.com:thevndrew/nix-packages.git"
    directory: "repos/nix-packages"
  secret_packages:
    url: "git@github.com:thevndrew/nix-secret-pkgs.git"
    directory: "repos/nix-secret-pkgs"
  neovim:
    url: "git@github.com:thevndrew/vndrew.nvim.git"
    directory: "repos/vndrew.nvim"
